name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - docs/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        #TODO this access token will expire and need to be updated, created from Colton Glick's account
        ACCESS_TOKEN: ${{ secrets.COLTON_ACCESS_TOKEN }}
        TARGET_REPO: LTL-AERO/OpenUAS
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: cd Documentation && npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
        #CNAME: https://www.xxx.com