name: Vuepress Build and Deploy
on:   
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: vuepress-build-and-deploy
      uses: intergiro/vuepress-deploy@fix_git_repo # temporary work around until jenkey2011/vuepress-deploy@master is updated. See https://github.com/jenkey2011/vuepress-deploy/pull/29
      env:
        #TODO this access token will expire and need to be updated, created from Colton Glick's account
        ACCESS_TOKEN: ${{ secrets.COLTON_ACCESS_TOKEN }}
        TARGET_REPO: Open-UAS/Open-UAS.github.io
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
        #CNAME: https://www.xxx.com
